#!/bin/bash

container_id=$(docker ps --format "table {{.ID}}\t{{.Names}}" \
    | grep -i 'ascapacitaphalconapi_php_' \
    | cut -d " " -f 1)

docker exec -it $container_id sh -c "cd /www/as-capacita-phalcon-api && composer $*"
